### ISSUE TITLE
Release a binary

### ISSUE THREAD

**Issue by ghost** [PichetGoulu/bubble-komga#1]
Hello, 

Thanks for your work and to share it as it is.

My two cents, could you please provide users with at least one apk. That really could help people to test your application.

Cheers

**Comment by PichetGoulu** [comment]
Hello,

I've published a signed .apk.

The .apk is signed with a newly created key, and not tied to the "Google Play Store", but it should works just fine.
Re-open this issue if you have trouble installing the .apk.

Cheers
